### PR TITLE
removed class grocery (collapsed with ingredients)

### LINKED ISSUE #17: reorganize entities - replace Grocery
replace Grocery with "Ingredient" but make it the contents of Grocery, also fix any calls to Grocery and Ingredient throughout the rest of the code to make sure it still works

### PR DESCRIPTION
**Pull request by hhpfiona**

### CODE REVIEW

**Review by parkhangorodsky — APPROVED** [review]
getting the following error when i run: /Users/paulamalla/IdeaProjects/BitByteBistro/src/main/java/view/SearchRecipeView.java:177:86
java: incompatible types: java.util.List<entity.Ingredient> cannot be converted to java.util.List<entity.Grocery>

**Review by parkhangorodsky — CHANGES_REQUESTED** [review]
getting the following error when i run: /Users/paulamalla/IdeaProjects/BitByteBistro/src/main/java/view/SearchRecipeView.java:177:86
java: incompatible types: java.util.List<entity.Ingredient> cannot be converted to java.util.List<entity.Grocery>

**Comment by hhpfiona** [comment]
changes made to resolve this problem noted by Paula: getting the following error when i run: /Users/paulamalla/IdeaProjects/BitByteBistro/src/main/java/view/SearchRecipeView.java:177:86
java: incompatible types: java.util.List<entity.Ingredient> cannot be converted to java.util.List<entity.Grocery>

please review

**Comment by hhpfiona** [comment]
still need to change grocery to ingredient in entities

**Review by seonghyunban — APPROVED** [review]
I think this should work.

**Pull request merged**
