### PR TITLE
Testing/nutrition display

### LINKED ISSUE #31: add testing for nutritionDisplay (and RecipeJSONHandler, NutritionJSONHandler)
adds the testing structure for these tests and writes the tests

### PR DESCRIPTION
**Pull request by parkhangorodsky**
adds all relevant testing for phase 1 deadline.

### CODE REVIEW

**Review by seonghyunban — APPROVED** [review]
Approved. I am sure you will fill some of the tests soon!!

**Comment by parkhangorodsky** [comment]
> Approved. I am sure you will fill some of the tests soon!!

some of them are actually very deeply in progress - but figured i'd rather either have empty or complete/working tests so i didnt push those changes for now

**Comment by RqedK** [comment]
> > Approved. I am sure you will fill some of the tests soon!!
> 
> some of them are actually very deeply in progress - but figured i'd rather either have empty or complete/working tests so i didnt push those changes for now

Yeah other than that looks good !

**Review by RqedK — APPROVED** [review]

**Review by hhpfiona — APPROVED** [review]
structure looks good, good place holder to add more testing in the future

**Pull request merged**
